### ISSUE TITLE
LiteIDE writes to AppData\Local

### ISSUE THREAD

**Issue by steronydh** [josephspurrier/golang-portable-windows#4]
Just to let you know that LiteIDE isn't perfectly portable, because it created a LiteIDE folder inside my user's AppData\Local folder, containing a "Hello World" go program.

**Comment by josephspurrier** [comment]
Yeah, that's actually a limitation of LiteIDE.

The goplay path is retrieved from here:
https://github.com/visualfc/liteide/blob/eddb51b5fd2c43836003ca52ab8db9ae4e588b78/liteidex/src/plugins/golangplay/goplaybrowser.cpp#L63

storagePath() is retrieved from here:
https://github.com/visualfc/liteide/blob/7bfa0821eb02e0b1e8219dcb5fc735fb5e823770/liteidex/src/liteapp/liteapp.cpp#L120

QStandardPaths::DataLocation points to AppData.

You may want to put in a ticket for LiteIDE.

**Comment by steronydh** [comment]
Thanks for the information!

**Comment by steronydh** [comment]
I  put in a ticket and it's already possible to make LiteIDE use local storage. Details [here](https://github.com/visualfc/liteide/issues/750).
