### ISSUE TITLE
Windows Defender finds Trojan Tiggre!Plock in pack.exe

### ISSUE THREAD

**Issue by kravlost** [josephspurrier/golang-portable-windows#8]
As title. Not sure if this is a false positive, but I've uninstalled it for now.

Version 1.10-1

Affected file: <installdir>\go\pkg\tool\windows_386\pack.exe

**Comment by papypom** [comment]
Same here ... Pity.

**Comment by josephspurrier** [comment]
Oh wow, that's crappy. I'll scan it on my machine. I've removed the download for now until I can determine why the false positive. Thanks for letting me know.

**Comment by SegoCode** [comment]
Let me check...

Name: pack.exe
SHA1: 200302a4c511cc810ffbc6d77e022d3444e71bf5
Use DLL: 
- kernel32.dll 
- winmm.dll 
- ws2_32.dll 

Strings: (Good) https://gist.github.com/SegoCode/780c64939effbf152fc6ec843412e230
Virustotal Analysis: [1/73](https://www.virustotal.com/gui/file/913ded88d235cd4841043f0fa6b98821d5bfd5b19f369963abe2b57e5b60dc7e/detection)

I think possibly a false positive, No files change, No external connections, 8 months on virustotal and just one heuristic detection.
